### PR TITLE
added the solution for the problem Bmail Computer Network from CodeForces in CPP(Link to the problem: https://codeforces.com/problemset/problem/1057/A Problem Number: 1057A)

### PR DESCRIPTION
**Pull request by Debashis08**
Link to the problem: https://codeforces.com/problemset/problem/1057/A
Problem Number: 1057A

### CODE REVIEW

**Comment by Sam071100** [comment]
Please mention the link to the question in the PR comment as well as the Number of the problem (for Ex: 334B)

**Comment by Debashis08** [comment]
Yes, Done.

**Comment by Sam071100** [comment]
Only Problem Number to be mentioned in PR heading. Both Link and Problem number should be mentioned in PR Comment.

**Comment by Sam071100** [comment]
Accepted

**Pull request merged**
